//------------------------------------------------------------------------
// Copyright(c) 2024 Carlos Bermejo.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"socket-plugin.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"socket-plugin VST3 (64Bit)"
#else
#define stringFileDescription	"socket-plugin VST3"
#endif
#define stringCompanyName		"Carlos Bermejo\0"
#define stringLegalCopyright	"Copyright(c) 2024 Carlos Bermejo."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
